services:
  postgres:
    image: postgres:18
    container_name: phonebook_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: phonebook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: phonebook_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  server:
    build: ./
    container_name: phonebook_server
    ports:
      - "5000:5000"
    environment:
      DB_HOST: postgres
      DB_NAME: phonebook
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data: